apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: my-registry
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  components:
    - kind: postgres
      managed: true
      overrides:
        resources:
          requests:
            cpu: 50m
    - kind: quay
      managed: true
      overrides:
        replicas: 2
        env:
          - name: QUAY_HOTRELOAD
            value: "true"
          - name: WORKER_COUNT_WEB
            value: "2"
          - name: WORKER_COUNT_REGISTRY
            value: "2"
        resources:
          requests:
            cpu: 1500m
            memory: 4Gi
          limits:
            cpu: '4'
            memory: 8Gi
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: false
    - kind: objectstorage	
      managed: true	
    - kind: route	
      managed: true	
    - kind: mirror	
      managed: true	
    - kind: monitoring	
      managed: false	
    - kind: tls	
      managed: true	
    - kind: clairpostgres	
      managed: true
