apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: my-registry
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  components:
    - kind: postgres
      managed: true
      overrides:
        resources:
          requests:
            cpu: 50m
    - kind: quay
      managed: true
      overrides:
        env:
          - name: QUAY_HOTRELOAD
            value: "true"
          - name: WORKER_COUNT_WEB
            value: "2"
          - name: WORKER_COUNT_REGISTRY
            value: "2"
        resources:
          requests:
            cpu: 2000m
            memory: 8Gi
          limits:
            cpu: 4000m
            memory: 8Gi
